behaviors:
  RocketAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
      gail:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: 'J:\Unity Projects\RocksRocketsAndRayguns\Assets\Demonstrations\RocketAI_0.demo'
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 2000
    summary_freq: 10000
    behavioral_cloning:
      demo_path: 'J:\Unity Projects\RocksRocketsAndRayguns\Assets\Demonstrations\RocketAI_0.demo'
      steps: 1000
      strength: 1.0
      samples_per_update: 0
